language: php

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
        
    fast_finish: true
    
install:
  - composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpspec run --format pretty
  - phpunit
